import Navbar from "../../components/navbarcomponents/Navbar";
import { NextAuthProvider } from "../../contexts/Provider";
import "./globals.css";
import { Roboto } from "next/font/google";
import { authOptions } from "./api/auth/[...nextauth]/route";
import { getServerSession } from "next-auth/next";
import Footer from "../../components/footer/Footer";

const roboto = Roboto({ weight: "400", subsets: ["latin"], display: "swap" });

export const metadata = {
  title: "Brand",
  description: "Generated by create next app",
  icon: "https://brandnewapp.netlify.app/icon.png",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={roboto.className}>
        {!session ? (
          <NextAuthProvider>{children}</NextAuthProvider>
        ) : (
          <NextAuthProvider>
            <Navbar />
            <main className="pt-[130px]">{children}</main>
            <Footer />
          </NextAuthProvider>
        )}
      </body>
    </html>
  );
}
